name: mango
description: "Mango - App de gestión de gastos personales"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Routing
  go_router: ^13.2.4

  # State management (MVVM)
  flutter_riverpod: ^2.5.1

  # Equatable para estados y entidades inmutables
  equatable: ^2.0.5

  # Helpers
  collection: ^1.18.0
  intl: ^0.19.0

  # UI extras
  flutter_slidable: ^4.0.0

  # Charts
  fl_chart: ^0.66.2

  # Firebase
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
