// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk_7iaUBZxR_n2dOFB1NcgaVFewlkNcUA',
    appId: '1:1050217396947:web:642fbcdacf52995161b226',
    messagingSenderId: '1050217396947',
    projectId: 'mangoapp-760b6',
    authDomain: 'mangoapp-760b6.firebaseapp.com',
    storageBucket: 'mangoapp-760b6.firebasestorage.app',
    measurementId: 'G-BJ98H9GTXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv2bZcEG7IoBR07a7G47S5WPCgk2cPCns',
    appId: '1:1050217396947:android:006fef4abf89729861b226',
    messagingSenderId: '1050217396947',
    projectId: 'mangoapp-760b6',
    storageBucket: 'mangoapp-760b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIDX4m9wLLqunUmKCjNBss6PcgPkIQL48',
    appId: '1:1050217396947:ios:d64ace184b58bffe61b226',
    messagingSenderId: '1050217396947',
    projectId: 'mangoapp-760b6',
    storageBucket: 'mangoapp-760b6.firebasestorage.app',
    iosBundleId: 'com.example.mango',
  );
}
